name = "Geomechanics"
uuid = "f1849530-a32b-11e9-2655-c7e7eedeacad"
authors = ["Santiago Cuervo"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
